"""Copy the generated Flux viewer and its provenance; never hand-edit the vendored JS."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import os


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--flux-root',type=Path,required=True)
    args=parser.parse_args()
    source=args.flux_root/'dist/flux-model3d-viewer.js'
    data=source.read_bytes()
    stamp_file=args.flux_root/'dist/flux-model3d-viewer.stamp.json'
    stamp=json.loads(stamp_file.read_text())
    digest=hashlib.sha256(data).hexdigest()
    if stamp.get('sha256')!=digest: raise SystemExit('Flux viewer stamp does not match generated bytes; rebuild it first')
    notice=args.flux_root/'dist/flux-model3d-THIRD-PARTY.txt'
    out=Path(__file__).resolve().parents[1]/'src/fluxplot/_viewer'
    out.mkdir(parents=True,exist_ok=True)
    for name,content in [('flux-model3d-viewer.min.js',data),('stamp.json',(json.dumps(stamp,sort_keys=True,indent=2)+'\n').encode()),('THIRD-PARTY.txt',notice.read_bytes())]:
        temp=out/(name+'.staging');temp.write_bytes(content);os.replace(temp,out/name)
    print(f'Synced Flux viewer {stamp.get("version","unknown")} {digest}')

if __name__=='__main__': main()
